server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
  file:
    path: /root/logs/seata

console:
  user:
    username: seata
    password: seata

sessionMode: db

seata:
  config:
    type: file
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: nacos:8848
      group: SEATA_GROUP
      cluster: default
  store:
    mode: db
    db:
      datasource: hikari
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://mysql:3306/seata_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      user: seata
      password: seata_local_pass
      min-conn: 5
      max-conn: 20
      query-limit: 100
      max-wait: 5000
      global-table: global_table
      branch-table: branch_table
      lock-table: lock_table
      distributed-lock-table: distributed_lock
  server:
    service-port: 8091
  security:
    secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
    tokenValidityInMilliseconds: 1800000
    csrf-ignore-urls: /metadata/v1/**
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.jpeg,/**/*.ico,/api/v1/auth/login,/version.json,/health,/error,/vgroup/v1/**
